//
// Copyright (c) 2017 by Farsight Security, Inc.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: sielink.proto

package sielink

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_DataMessage     MessageType = 0
	MessageType_TopologyMessage MessageType = 1
	MessageType_AlertMessage    MessageType = 2
	MessageType_Heartbeat       MessageType = 3
	MessageType_Shutdown        MessageType = 4
	MessageType_Finished        MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "DataMessage",
		1: "TopologyMessage",
		2: "AlertMessage",
		3: "Heartbeat",
		4: "Shutdown",
		5: "Finished",
	}
	MessageType_value = map[string]int32{
		"DataMessage":     0,
		"TopologyMessage": 1,
		"AlertMessage":    2,
		"Heartbeat":       3,
		"Shutdown":        4,
		"Finished":        5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_sielink_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_sielink_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MessageType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MessageType(num)
	return nil
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_sielink_proto_rawDescGZIP(), []int{0}
}

type PayloadType int32

const (
	PayloadType_NmsgContainer    PayloadType = 1
	PayloadType_LogRecord        PayloadType = 2
	PayloadType_AccountingRecord PayloadType = 3
)

// Enum value maps for PayloadType.
var (
	PayloadType_name = map[int32]string{
		1: "NmsgContainer",
		2: "LogRecord",
		3: "AccountingRecord",
	}
	PayloadType_value = map[string]int32{
		"NmsgContainer":    1,
		"LogRecord":        2,
		"AccountingRecord": 3,
	}
)

func (x PayloadType) Enum() *PayloadType {
	p := new(PayloadType)
	*p = x
	return p
}

func (x PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_sielink_proto_enumTypes[1].Descriptor()
}

func (PayloadType) Type() protoreflect.EnumType {
	return &file_sielink_proto_enumTypes[1]
}

func (x PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PayloadType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PayloadType(num)
	return nil
}

// Deprecated: Use PayloadType.Descriptor instead.
func (PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_sielink_proto_rawDescGZIP(), []int{1}
}

type CompressionType int32

const (
	CompressionType_None    CompressionType = 0
	CompressionType_Gzip    CompressionType = 1
	CompressionType_Deflate CompressionType = 2
	CompressionType_LZ4     CompressionType = 3
)

// Enum value maps for CompressionType.
var (
	CompressionType_name = map[int32]string{
		0: "None",
		1: "Gzip",
		2: "Deflate",
		3: "LZ4",
	}
	CompressionType_value = map[string]int32{
		"None":    0,
		"Gzip":    1,
		"Deflate": 2,
		"LZ4":     3,
	}
)

func (x CompressionType) Enum() *CompressionType {
	p := new(CompressionType)
	*p = x
	return p
}

func (x CompressionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompressionType) Descriptor() protoreflect.EnumDescriptor {
	return file_sielink_proto_enumTypes[2].Descriptor()
}

func (CompressionType) Type() protoreflect.EnumType {
	return &file_sielink_proto_enumTypes[2]
}

func (x CompressionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CompressionType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CompressionType(num)
	return nil
}

// Deprecated: Use CompressionType.Descriptor instead.
func (CompressionType) EnumDescriptor() ([]byte, []int) {
	return file_sielink_proto_rawDescGZIP(), []int{2}
}

type AlertLevel int32

const (
	AlertLevel_Informational    AlertLevel = 0
	AlertLevel_Warning          AlertLevel = 1
	AlertLevel_RecoverableError AlertLevel = 2
	AlertLevel_FatalError       AlertLevel = 3
)

// Enum value maps for AlertLevel.
var (
	AlertLevel_name = map[int32]string{
		0: "Informational",
		1: "Warning",
		2: "RecoverableError",
		3: "FatalError",
	}
	AlertLevel_value = map[string]int32{
		"Informational":    0,
		"Warning":          1,
		"RecoverableError": 2,
		"FatalError":       3,
	}
)

func (x AlertLevel) Enum() *AlertLevel {
	p := new(AlertLevel)
	*p = x
	return p
}

func (x AlertLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_sielink_proto_enumTypes[3].Descriptor()
}

func (AlertLevel) Type() protoreflect.EnumType {
	return &file_sielink_proto_enumTypes[3]
}

func (x AlertLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AlertLevel) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AlertLevel(num)
	return nil
}

// Deprecated: Use AlertLevel.Descriptor instead.
func (AlertLevel) EnumDescriptor() ([]byte, []int) {
	return file_sielink_proto_rawDescGZIP(), []int{3}
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocolVersion lists all versions of the protocol
	// supported by the message sender. Both peers must
	// use the highest mutually supported version.
	ProtocolVersion []uint32 `protobuf:"varint,1,rep,name=protocolVersion" json:"protocolVersion,omitempty"`
	// The messageType informs the recipient which of the
	// following fields are expected to be populated, if any.
	MessageType *MessageType `protobuf:"varint,2,req,name=messageType,enum=sielink.MessageType" json:"messageType,omitempty"`
	// The Payload is populated only for messages of type DataMessage.
	Payload *Payload `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	// The Topology is populated only for messages of type TopologyMessage.
	Topology *Topology `protobuf:"bytes,4,opt,name=topology" json:"topology,omitempty"`
	// The heartbeat value is a time interval in milliseconds,
	// and tells the recipient to expect another heartbeat within
	// that time interval.
	//
	// heartbeat can be set for any message type. Type HeartbeatMessage
	// can be used if only the heartbeat is sent.
	Heartbeat *uint32 `protobuf:"varint,5,opt,name=heartbeat" json:"heartbeat,omitempty"`
	// Alert is populated only for messages of type AlertMessage.
	Alert         *Alert `protobuf:"bytes,6,opt,name=alert" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_sielink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_sielink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_sielink_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetProtocolVersion() []uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return nil
}

func (x *Message) GetMessageType() MessageType {
	if x != nil && x.MessageType != nil {
		return *x.MessageType
	}
	return MessageType_DataMessage
}

func (x *Message) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetTopology() *Topology {
	if x != nil {
		return x.Topology
	}
	return nil
}

func (x *Message) GetHeartbeat() uint32 {
	if x != nil && x.Heartbeat != nil {
		return *x.Heartbeat
	}
	return 0
}

func (x *Message) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

// A Payload carries data for eventual publication or other processing.
type Payload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data is segmented into channels, some of which correspond
	// to SIE channel numbers.
	Channel         *uint32          `protobuf:"varint,1,req,name=channel" json:"channel,omitempty"`
	PayloadType     *PayloadType     `protobuf:"varint,2,opt,name=payloadType,enum=sielink.PayloadType" json:"payloadType,omitempty"`
	CompressionType *CompressionType `protobuf:"varint,3,opt,name=compressionType,enum=sielink.CompressionType" json:"compressionType,omitempty"`
	Data            []byte           `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	// The loss markers `linkLoss` and `pathLoss` track
	// loss of sielink Payloads from queue overflows.
	// The `linkLoss` counters are added to `pathLoss`
	// and reset on each hop.
	LinkLoss *LossCounter `protobuf:"bytes,5,opt,name=linkLoss" json:"linkLoss,omitempty"`
	PathLoss *LossCounter `protobuf:"bytes,6,opt,name=pathLoss" json:"pathLoss,omitempty"`
	// sourceSite identifies the site at which the Payload
	// was first submitted.
	SourceSite *uint32 `protobuf:"varint,7,opt,name=sourceSite" json:"sourceSite,omitempty"`
	// sourceContributor contains the SIE source id of the
	// uploading client, if known. The identifiers in the
	// enclosed payloads (for NmsgContainer payloadType) are
	// not modified in transit.
	SourceContributor *uint32 `protobuf:"varint,8,opt,name=sourceContributor" json:"sourceContributor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_sielink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_sielink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_sielink_proto_rawDescGZIP(), []int{1}
}

func (x *Payload) GetChannel() uint32 {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return 0
}

func (x *Payload) GetPayloadType() PayloadType {
	if x != nil && x.PayloadType != nil {
		return *x.PayloadType
	}
	return PayloadType_NmsgContainer
}

func (x *Payload) GetCompressionType() CompressionType {
	if x != nil && x.CompressionType != nil {
		return *x.CompressionType
	}
	return CompressionType_None
}

func (x *Payload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Payload) GetLinkLoss() *LossCounter {
	if x != nil {
		return x.LinkLoss
	}
	return nil
}

func (x *Payload) GetPathLoss() *LossCounter {
	if x != nil {
		return x.PathLoss
	}
	return nil
}

func (x *Payload) GetSourceSite() uint32 {
	if x != nil && x.SourceSite != nil {
		return *x.SourceSite
	}
	return 0
}

func (x *Payload) GetSourceContributor() uint32 {
	if x != nil && x.SourceContributor != nil {
		return *x.SourceContributor
	}
	return 0
}

type LossCounter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         *uint64                `protobuf:"varint,1,opt,name=bytes" json:"bytes,omitempty"`
	Payloads      *uint64                `protobuf:"varint,2,opt,name=payloads" json:"payloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LossCounter) Reset() {
	*x = LossCounter{}
	mi := &file_sielink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LossCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LossCounter) ProtoMessage() {}

func (x *LossCounter) ProtoReflect() protoreflect.Message {
	mi := &file_sielink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LossCounter.ProtoReflect.Descriptor instead.
func (*LossCounter) Descriptor() ([]byte, []int) {
	return file_sielink_proto_rawDescGZIP(), []int{2}
}

func (x *LossCounter) GetBytes() uint64 {
	if x != nil && x.Bytes != nil {
		return *x.Bytes
	}
	return 0
}

func (x *LossCounter) GetPayloads() uint64 {
	if x != nil && x.Payloads != nil {
		return *x.Payloads
	}
	return 0
}

// The exchange of Topology messages coordinates the routing of
// Payloads among the submission hosts.
type Topology struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `path` contains the shortest known path for each known site,
	// except for the site receiving the topology message.
	Path []*Path `protobuf:"bytes,1,rep,name=path" json:"path,omitempty"`
	// `subscription` selects the data the sender wishes to receive.
	Subscription  []*Subscription `protobuf:"bytes,2,rep,name=subscription" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topology) Reset() {
	*x = Topology{}
	mi := &file_sielink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topology) ProtoMessage() {}

func (x *Topology) ProtoReflect() protoreflect.Message {
	mi := &file_sielink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topology.ProtoReflect.Descriptor instead.
func (*Topology) Descriptor() ([]byte, []int) {
	return file_sielink_proto_rawDescGZIP(), []int{3}
}

func (x *Topology) GetPath() []*Path {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Topology) GetSubscription() []*Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

// A Path is an ordered list of sites with a metric reflecting the
// cost of traversing the full path. The sites are listed in order
// from the furthest (destination) to the closest (next hop).
type Path struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *uint64                `protobuf:"varint,1,req,name=metric" json:"metric,omitempty"`
	Site          []uint32               `protobuf:"varint,2,rep,name=site" json:"site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_sielink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_sielink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_sielink_proto_rawDescGZIP(), []int{4}
}

func (x *Path) GetMetric() uint64 {
	if x != nil && x.Metric != nil {
		return *x.Metric
	}
	return 0
}

func (x *Path) GetSite() []uint32 {
	if x != nil {
		return x.Site
	}
	return nil
}

// Subscription messages supply a list of channels the sender wishes
// to receive, and an optional source site. If the source site is populated
// and nonzero, the message reqeusts only data submitted to that site on the
// supplied channels. Otherwise, it requests data from any site.
type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceSite    *uint32                `protobuf:"varint,1,opt,name=sourceSite" json:"sourceSite,omitempty"`
	Channel       []uint32               `protobuf:"varint,2,rep,name=channel" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_sielink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_sielink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_sielink_proto_rawDescGZIP(), []int{5}
}

func (x *Subscription) GetSourceSite() uint32 {
	if x != nil && x.SourceSite != nil {
		return *x.SourceSite
	}
	return 0
}

func (x *Subscription) GetChannel() []uint32 {
	if x != nil {
		return x.Channel
	}
	return nil
}

// Alert messages are used to communicate error conditions and
// other out-of-band information to the peer. With the exception
// of FatalError alerts, they do not affect the operation of the
// protocol.
type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         *AlertLevel            `protobuf:"varint,1,req,name=level,enum=sielink.AlertLevel" json:"level,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Code          *uint32                `protobuf:"varint,3,opt,name=code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_sielink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_sielink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_sielink_proto_rawDescGZIP(), []int{6}
}

func (x *Alert) GetLevel() AlertLevel {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return AlertLevel_Informational
}

func (x *Alert) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *Alert) GetCode() uint32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

var File_sielink_proto protoreflect.FileDescriptor

const file_sielink_proto_rawDesc = "" +
	"\n" +
	"\rsielink.proto\x12\asielink\"\x8a\x02\n" +
	"\aMessage\x12(\n" +
	"\x0fprotocolVersion\x18\x01 \x03(\rR\x0fprotocolVersion\x126\n" +
	"\vmessageType\x18\x02 \x02(\x0e2\x14.sielink.MessageTypeR\vmessageType\x12*\n" +
	"\apayload\x18\x03 \x01(\v2\x10.sielink.PayloadR\apayload\x12-\n" +
	"\btopology\x18\x04 \x01(\v2\x11.sielink.TopologyR\btopology\x12\x1c\n" +
	"\theartbeat\x18\x05 \x01(\rR\theartbeat\x12$\n" +
	"\x05alert\x18\x06 \x01(\v2\x0e.sielink.AlertR\x05alert\"\xe5\x02\n" +
	"\aPayload\x12\x18\n" +
	"\achannel\x18\x01 \x02(\rR\achannel\x126\n" +
	"\vpayloadType\x18\x02 \x01(\x0e2\x14.sielink.PayloadTypeR\vpayloadType\x12B\n" +
	"\x0fcompressionType\x18\x03 \x01(\x0e2\x18.sielink.CompressionTypeR\x0fcompressionType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x120\n" +
	"\blinkLoss\x18\x05 \x01(\v2\x14.sielink.LossCounterR\blinkLoss\x120\n" +
	"\bpathLoss\x18\x06 \x01(\v2\x14.sielink.LossCounterR\bpathLoss\x12\x1e\n" +
	"\n" +
	"sourceSite\x18\a \x01(\rR\n" +
	"sourceSite\x12,\n" +
	"\x11sourceContributor\x18\b \x01(\rR\x11sourceContributor\"?\n" +
	"\vLossCounter\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\x04R\x05bytes\x12\x1a\n" +
	"\bpayloads\x18\x02 \x01(\x04R\bpayloads\"h\n" +
	"\bTopology\x12!\n" +
	"\x04path\x18\x01 \x03(\v2\r.sielink.PathR\x04path\x129\n" +
	"\fsubscription\x18\x02 \x03(\v2\x15.sielink.SubscriptionR\fsubscription\"2\n" +
	"\x04Path\x12\x16\n" +
	"\x06metric\x18\x01 \x02(\x04R\x06metric\x12\x12\n" +
	"\x04site\x18\x02 \x03(\rR\x04site\"H\n" +
	"\fSubscription\x12\x1e\n" +
	"\n" +
	"sourceSite\x18\x01 \x01(\rR\n" +
	"sourceSite\x12\x18\n" +
	"\achannel\x18\x02 \x03(\rR\achannel\"`\n" +
	"\x05Alert\x12)\n" +
	"\x05level\x18\x01 \x02(\x0e2\x13.sielink.AlertLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\rR\x04code*p\n" +
	"\vMessageType\x12\x0f\n" +
	"\vDataMessage\x10\x00\x12\x13\n" +
	"\x0fTopologyMessage\x10\x01\x12\x10\n" +
	"\fAlertMessage\x10\x02\x12\r\n" +
	"\tHeartbeat\x10\x03\x12\f\n" +
	"\bShutdown\x10\x04\x12\f\n" +
	"\bFinished\x10\x05*E\n" +
	"\vPayloadType\x12\x11\n" +
	"\rNmsgContainer\x10\x01\x12\r\n" +
	"\tLogRecord\x10\x02\x12\x14\n" +
	"\x10AccountingRecord\x10\x03*;\n" +
	"\x0fCompressionType\x12\b\n" +
	"\x04None\x10\x00\x12\b\n" +
	"\x04Gzip\x10\x01\x12\v\n" +
	"\aDeflate\x10\x02\x12\a\n" +
	"\x03LZ4\x10\x03*R\n" +
	"\n" +
	"AlertLevel\x12\x11\n" +
	"\rInformational\x10\x00\x12\v\n" +
	"\aWarning\x10\x01\x12\x14\n" +
	"\x10RecoverableError\x10\x02\x12\x0e\n" +
	"\n" +
	"FatalError\x10\x03"

var (
	file_sielink_proto_rawDescOnce sync.Once
	file_sielink_proto_rawDescData []byte
)

func file_sielink_proto_rawDescGZIP() []byte {
	file_sielink_proto_rawDescOnce.Do(func() {
		file_sielink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sielink_proto_rawDesc), len(file_sielink_proto_rawDesc)))
	})
	return file_sielink_proto_rawDescData
}

var file_sielink_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_sielink_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sielink_proto_goTypes = []any{
	(MessageType)(0),     // 0: sielink.MessageType
	(PayloadType)(0),     // 1: sielink.PayloadType
	(CompressionType)(0), // 2: sielink.CompressionType
	(AlertLevel)(0),      // 3: sielink.AlertLevel
	(*Message)(nil),      // 4: sielink.Message
	(*Payload)(nil),      // 5: sielink.Payload
	(*LossCounter)(nil),  // 6: sielink.LossCounter
	(*Topology)(nil),     // 7: sielink.Topology
	(*Path)(nil),         // 8: sielink.Path
	(*Subscription)(nil), // 9: sielink.Subscription
	(*Alert)(nil),        // 10: sielink.Alert
}
var file_sielink_proto_depIdxs = []int32{
	0,  // 0: sielink.Message.messageType:type_name -> sielink.MessageType
	5,  // 1: sielink.Message.payload:type_name -> sielink.Payload
	7,  // 2: sielink.Message.topology:type_name -> sielink.Topology
	10, // 3: sielink.Message.alert:type_name -> sielink.Alert
	1,  // 4: sielink.Payload.payloadType:type_name -> sielink.PayloadType
	2,  // 5: sielink.Payload.compressionType:type_name -> sielink.CompressionType
	6,  // 6: sielink.Payload.linkLoss:type_name -> sielink.LossCounter
	6,  // 7: sielink.Payload.pathLoss:type_name -> sielink.LossCounter
	8,  // 8: sielink.Topology.path:type_name -> sielink.Path
	9,  // 9: sielink.Topology.subscription:type_name -> sielink.Subscription
	3,  // 10: sielink.Alert.level:type_name -> sielink.AlertLevel
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_sielink_proto_init() }
func file_sielink_proto_init() {
	if File_sielink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sielink_proto_rawDesc), len(file_sielink_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sielink_proto_goTypes,
		DependencyIndexes: file_sielink_proto_depIdxs,
		EnumInfos:         file_sielink_proto_enumTypes,
		MessageInfos:      file_sielink_proto_msgTypes,
	}.Build()
	File_sielink_proto = out.File
	file_sielink_proto_goTypes = nil
	file_sielink_proto_depIdxs = nil
}
